version: '3.8'
services:
  lyrics-downloader:
    build: .
    container_name: lyrics-downloader
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
